trigger:
  branches:
    include:
      - main  # The pipeline runs when code is pushed to the 'main' branch.

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux agent.

steps:
- script: echo "Step 1 Initializing..."  
  displayName: 'Step 1 - Initialization'

