trigger:
  branches:
    include:
      - main  # The pipeline runs when code is pushed to the 'main' branch.

pool:
  vmImage: 'default'  # Use a Linux agent.

steps:
- script: echo "Hello, Azure Pipeline!"  # Simple echo command
  displayName: 'Echo Words'
